### ISSUE TITLE
Log to file?

### ISSUE THREAD

**Issue by essenciary** [oxinabox/OhMyLog.jl#2]
Can it write to multiple logs at once, including console and file?

**Comment by oxinabox** [comment]
No.
That isn't the goal here.

A logging demultiplexer seems reasonable to build,
based on the Base/StdLib logging infrastructure.



Or one could use https://github.com/invenia/Memento.jl
but I think that has entirely its own set of commands that don't interact with the inbuilt logging commands.
(@iamed2,  is that right?)

**Comment by iamed2** [comment]
You can redirect stdlib logging to Memento but there's some lost efficiency there. 

Memento is definitely the current best choice for logging to multiple places at once, given that it's perhaps the only choice.

**Comment by oxinabox** [comment]
@essenciary 
for fun and as an exercise I put together a quick package. 
It isn't as full featured as Memento.

But it is pure stdlib logging.

https://github.com/oxinabox/LoggingExtras.jl

**Comment by essenciary** [comment]
Thank you all for your help. 
@oxinabox Thanks, I'll give it a try!
